services:
  app:
    build: .
    ports:
      - "3042:3042"
    environment:
      - NODE_ENV=production
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - PORT=3042
    restart: unless-stopped 