services:
  app:
    build:
      context: .
      args:
        - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    restart: unless-stopped 